### ISSUE TITLE
Option for not extracting DLs

### ISSUE THREAD

**Issue by Luux** [Luux/ARBSMapDo#10]
For uploading maps for the Quest, files are uploaded as *.zip. Implement an option for not extracting downloaded files.

**Comment by Luux** [comment]
@I4MTRUE @Surferlul I added this functionality which should be functional with the commit https://github.com/Luux/ARBSMapDo/commit/2324d5b0a1786fcf1b9829a25aa7ab942addd2ad

Don't forget to --rescan if you're switching between a Quest-ready zip-directory and your regular installation. I recommend to use two different presets (w/ different paths and levelhash-cachefile!) here if you want to use ARBSMapDo for both PC and Quest.

This functionality also works _in combination_ with the recently added manual download and playlist functions. So if you want to keep PC and Quest synched, you can add your regular new maps to a growing playlist and then import this local playlist for the Quest version.

However, these wild combinations definitely need some testing and maybe polishing. The tool is pretty mighty with the latest additions and I cannot test every possible combination myself :D

**Comment by I4MTRUE** [comment]
Thank You :DD

**Comment by Luux** [comment]
Whoops, almost forgot: the relevant option is --noextract

I need to update the README prior to the next release to include all the new stuff :)
