### ISSUE TITLE
unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by untuned** [Luux/ARBSMapDo#18]
Here's the error:
```
Scanning already existing maps...
Traceback (most recent call last):
  File "D:\Documents\bs\ARBSMapDo\arbsmapdo.py", line 331, in <module>
    downloader = advanced_downloader(config_handler.config)
  File "D:\Documents\bs\ARBSMapDo\downloader.py", line 61, in __init__
    self.cache = cache.Cache(config)
  File "D:\Documents\bs\ARBSMapDo\cache.py", line 35, in __init__
    self.update_levelhash_cache()
  File "D:\Documents\bs\ARBSMapDo\cache.py", line 143, in update_levelhash_cache
    levelhash = utils.calculate_Level_hash_from_dir(self.download_dir.joinpath(entry.name))
  File "D:\Documents\bs\ARBSMapDo\utils.py", line 62, in calculate_Level_hash_from_dir
    info_data = json.loads(info_binary, encoding="utf-8")
  File "C:\Python39\lib\json\__init__.py", line 359, in loads
    return cls(**kw).decode(s)
TypeError: __init__() got an unexpected keyword argument 'encoding'
```

**Comment by Luux** [comment]
Hi,
good spot! The encoding parameter of json.loads got removed in Python 3.9. the solution should be to simply change
`info_data = json.loads(info_binary, encoding="utf-8")`
to
`info_data = json.loads(info_binary)`

**Comment by Luux** [comment]
This should be fixed in https://github.com/Luux/ARBSMapDo/commit/841b210877238e40792b7bb46abe729157caf488 - can you confirm that?

**Comment by untuned** [comment]
> This should be fixed in [841b210](https://github.com/Luux/ARBSMapDo/commit/841b210877238e40792b7bb46abe729157caf488) - can you confirm that?

Got a few new errors:
![](https://untnd.me/6iqS8_lRXV)

**Comment by Luux** [comment]
Hmm, that looks like some kind of connection error that occurs during the request to scoresaber. It seems that the connection to the scoresaber API broke for some reason.  I could not reproduce this error with a fresh python 3.9 environment. It is possible that the scoresaber server simply had some hickups. Did that occur multiple times? If so: which filtering options did you use?

**Comment by untuned** [comment]
> Hmm, that looks like some kind of connection error that occurs during the request to scoresaber. It seems that the connection to the scoresaber API broke for some reason. I could not reproduce this error with a fresh python 3.9 environment. It is possible that the scoresaber server simply had some hickups. Did that occur multiple times? If so: which filtering options did you use?

Must have been, it works now! While I'm here, is it possible that songs could be named as they are downloaded from BeatSaver? Example: `13c2a (Ruler of Everything - Thandwichis)`

**Comment by Luux** [comment]
Do you mean the ingame name or the directory/zip name of the downloaded map? 

The directory name is determined by the _get_level_dirname function at https://github.com/Luux/ARBSMapDo/blob/master/downloader.py#L424 This can be edited for custom formats if needed for some reason. Currently, the naming scheme is fixed, however if there are specific use cases where another naming format makes sense, we could implement that if it seems useful enough ;)

However, the ingame name is determined by the info.dat file for each map. The content of the info.dat is included in the map hash calculation - the hashes are unique identifiers for each map which are not only used by ARBSMapDo, but also by Scoresaber to identify a song. Changing the ingame level name would therefore imply that the hash changes, which would be bad.

**Comment by untuned** [comment]
> Do you mean the ingame name or the directory/zip name of the downloaded map?
> 
> The directory name is determined by the _get_level_dirname function at https://github.com/Luux/ARBSMapDo/blob/master/downloader.py#L424 This can be edited for custom formats if needed for some reason. Currently, the naming scheme is fixed, however if there are specific use cases where another naming format makes sense, we could implement that if it seems useful enough ;)
> 
> However, the ingame name is determined by the info.dat file for each map. The content of the info.dat is included in the map hash calculation - the hashes are unique identifiers for each map which are not only used by ARBSMapDo, but also by Scoresaber to identify a song. Changing the ingame level name would therefore imply that the hash changes, which would be bad.

I meant naming the folder the same as if you were downloading it through BeatSaver using the one-click install.

**Comment by Luux** [comment]
Sorry for the very late reply, I was very busy in the last weeks and somehow forgot about that one. I changed the directory name in https://github.com/Luux/ARBSMapDo/commit/1bf274ba1f8aa1a1ee5b0d829b6c33154decf97f since I do not need to include the hashes anymore in the newer versions.

**Comment by untuned** [comment]
Nice! Found another bug using the latest commit though.. Seems to have hit the rate limit for downloading songs.
![](https://untnd.me/uyOyEJfZh)

**Comment by Luux** [comment]
Hmm, usually the cache that uses the scraped data should prevent hitting the rate limit on beatsaver... I'll have a look on the evening. Can you specify the options you used?

**Comment by untuned** [comment]
> Hmm, usually the cache that uses the scraped data should prevent hitting the rate limit on beatsaver... I'll have a look on the evening. Can you specify the options you used?

Only used default options, and set it to 100 maps to download. It got rate limited after 60 fetches I believe.

**Comment by untuned** [comment]
Here's a bit more of a preview of what's going on:
![](https://untnd.me/d2CzblvKm)

**Comment by Luux** [comment]
I found the bug. The reason was that in https://github.com/andruzzzhka/BeatSaberScrappedData, at some point the hashes changed to uppercase strings instead of lowercase.
See for example https://raw.githubusercontent.com/andruzzzhka/BeatSaberScrappedData/e3b7e58e08bda461b9db773c164301cd99e42a6a/beatSaverScrappedData.json vs https://raw.githubusercontent.com/andruzzzhka/BeatSaberScrappedData/master/beatSaverScrappedData.json

That caused requested hashes being a cache miss in ARBSMapDo and therefore more requests to BeatSaver than usually. The cache should work again properly with https://github.com/Luux/ARBSMapDo/commit/1339b74cd379ec2a092e2fcf29c9b992b8ab6f4b and https://github.com/Luux/ARBSMapDo/releases/tag/v0.4.2

**Comment by untuned** [comment]
> I found the bug. The reason was that in https://github.com/andruzzzhka/BeatSaberScrappedData, at some point the hashes changed to uppercase strings instead of lowercase.
> See for example https://raw.githubusercontent.com/andruzzzhka/BeatSaberScrappedData/e3b7e58e08bda461b9db773c164301cd99e42a6a/beatSaverScrappedData.json vs https://raw.githubusercontent.com/andruzzzhka/BeatSaberScrappedData/master/beatSaverScrappedData.json
> 
> That caused requested hashes being a cache miss in ARBSMapDo and therefore more requests to BeatSaver than usually. The cache should work again properly with [1339b74](https://github.com/Luux/ARBSMapDo/commit/1339b74cd379ec2a092e2fcf29c9b992b8ab6f4b) and https://github.com/Luux/ARBSMapDo/releases/tag/v0.4.2

This worked! Thank you so much :)
